import type { Generator } from "@ozpulse/shared";

export const MOCK_GENERATORS: Generator[] = [
  // ─── NSW Coal ───
  { duid: "BW01", stationName: "Bayswater", participantName: "AGL Energy", fuelTech: "black_coal", fuelGroup: "coal", regionId: "NSW1", state: "NSW", latitude: -32.3940, longitude: 150.9780, maxCapacityMW: 2640, registeredCapacityMW: 2640, currentOutputMW: 2100, dispatchType: "scheduled", status: "operating", commissionedYear: 1985, expectedClosureYear: 2033 },
  { duid: "ER01", stationName: "Eraring", participantName: "Origin Energy", fuelTech: "black_coal", fuelGroup: "coal", regionId: "NSW1", state: "NSW", latitude: -33.0705, longitude: 151.5280, maxCapacityMW: 2880, registeredCapacityMW: 2880, currentOutputMW: 2200, dispatchType: "scheduled", status: "operating", commissionedYear: 1982, expectedClosureYear: 2027 },
  { duid: "VP05", stationName: "Vales Point B", participantName: "Delta Electricity", fuelTech: "black_coal", fuelGroup: "coal", regionId: "NSW1", state: "NSW", latitude: -33.1580, longitude: 151.5340, maxCapacityMW: 1320, registeredCapacityMW: 1320, currentOutputMW: 950, dispatchType: "scheduled", status: "operating", commissionedYear: 1978, expectedClosureYear: 2029 },
  { duid: "MP01", stationName: "Mount Piper", participantName: "EnergyAustralia", fuelTech: "black_coal", fuelGroup: "coal", regionId: "NSW1", state: "NSW", latitude: -33.4170, longitude: 150.0560, maxCapacityMW: 1400, registeredCapacityMW: 1400, currentOutputMW: 1100, dispatchType: "scheduled", status: "operating", commissionedYear: 1993, expectedClosureYear: 2040 },
  { duid: "LD04", stationName: "Liddell", participantName: "AGL Energy", fuelTech: "black_coal", fuelGroup: "coal", regionId: "NSW1", state: "NSW", latitude: -32.3710, longitude: 150.9690, maxCapacityMW: 2000, registeredCapacityMW: 2000, currentOutputMW: 0, dispatchType: "scheduled", status: "retired", commissionedYear: 1971, expectedClosureYear: 2023 },

  // ─── VIC Brown Coal ───
  { duid: "LYA1", stationName: "Loy Yang A", participantName: "AGL Energy", fuelTech: "brown_coal", fuelGroup: "coal", regionId: "VIC1", state: "VIC", latitude: -38.2560, longitude: 146.5930, maxCapacityMW: 2210, registeredCapacityMW: 2210, currentOutputMW: 1800, dispatchType: "scheduled", status: "operating", commissionedYear: 1984, expectedClosureYear: 2035 },
  { duid: "LYB1", stationName: "Loy Yang B", participantName: "Alinta Energy", fuelTech: "brown_coal", fuelGroup: "coal", regionId: "VIC1", state: "VIC", latitude: -38.2580, longitude: 146.5960, maxCapacityMW: 1000, registeredCapacityMW: 1000, currentOutputMW: 800, dispatchType: "scheduled", status: "operating", commissionedYear: 1993, expectedClosureYear: 2028 },
  { duid: "YWPS1", stationName: "Yallourn", participantName: "EnergyAustralia", fuelTech: "brown_coal", fuelGroup: "coal", regionId: "VIC1", state: "VIC", latitude: -38.1810, longitude: 146.3890, maxCapacityMW: 1480, registeredCapacityMW: 1480, currentOutputMW: 1100, dispatchType: "scheduled", status: "operating", commissionedYear: 1974, expectedClosureYear: 2028 },

  // ─── QLD Coal ───
  { duid: "CALL_A", stationName: "Callide B", participantName: "CS Energy", fuelTech: "black_coal", fuelGroup: "coal", regionId: "QLD1", state: "QLD", latitude: -24.4110, longitude: 150.5280, maxCapacityMW: 700, registeredCapacityMW: 700, currentOutputMW: 550, dispatchType: "scheduled", status: "operating", commissionedYear: 1988, expectedClosureYear: 2036 },
  { duid: "CALL_C", stationName: "Callide C", participantName: "Intergen", fuelTech: "black_coal", fuelGroup: "coal", regionId: "QLD1", state: "QLD", latitude: -24.4130, longitude: 150.5300, maxCapacityMW: 810, registeredCapacityMW: 810, currentOutputMW: 620, dispatchType: "scheduled", status: "operating", commissionedYear: 2001, expectedClosureYear: 2051 },
  { duid: "GLADSTONE", stationName: "Gladstone", participantName: "NRG Gladstone", fuelTech: "black_coal", fuelGroup: "coal", regionId: "QLD1", state: "QLD", latitude: -23.8520, longitude: 151.2720, maxCapacityMW: 1680, registeredCapacityMW: 1680, currentOutputMW: 1300, dispatchType: "scheduled", status: "operating", commissionedYear: 1976, expectedClosureYear: 2035 },
  { duid: "TARONG_1", stationName: "Tarong", participantName: "Stanwell", fuelTech: "black_coal", fuelGroup: "coal", regionId: "QLD1", state: "QLD", latitude: -26.7680, longitude: 151.9170, maxCapacityMW: 1400, registeredCapacityMW: 1400, currentOutputMW: 1050, dispatchType: "scheduled", status: "operating", commissionedYear: 1984, expectedClosureYear: 2036 },
  { duid: "KPP_1", stationName: "Kogan Creek", participantName: "CS Energy", fuelTech: "black_coal", fuelGroup: "coal", regionId: "QLD1", state: "QLD", latitude: -26.9370, longitude: 150.7830, maxCapacityMW: 750, registeredCapacityMW: 750, currentOutputMW: 680, dispatchType: "scheduled", status: "operating", commissionedYear: 2007, expectedClosureYear: 2042 },
  { duid: "STAN_1", stationName: "Stanwell", participantName: "Stanwell Corp", fuelTech: "black_coal", fuelGroup: "coal", regionId: "QLD1", state: "QLD", latitude: -23.4980, longitude: 150.3260, maxCapacityMW: 1460, registeredCapacityMW: 1460, currentOutputMW: 1100, dispatchType: "scheduled", status: "operating", commissionedYear: 1993, expectedClosureYear: 2046 },

  // ─── Gas ───
  { duid: "TALG1", stationName: "Tallawarra B", participantName: "EnergyAustralia", fuelTech: "gas_ccgt", fuelGroup: "gas", regionId: "NSW1", state: "NSW", latitude: -34.4340, longitude: 150.8580, maxCapacityMW: 316, registeredCapacityMW: 316, currentOutputMW: 200, dispatchType: "scheduled", status: "operating", commissionedYear: 2023 },
  { duid: "TORRA1", stationName: "Torrens Island A", participantName: "AGL Energy", fuelTech: "gas_steam", fuelGroup: "gas", regionId: "SA1", state: "SA", latitude: -34.7780, longitude: 138.5220, maxCapacityMW: 480, registeredCapacityMW: 480, currentOutputMW: 150, dispatchType: "scheduled", status: "operating", commissionedYear: 1967, expectedClosureYear: 2026 },
  { duid: "TORRB1", stationName: "Torrens Island B", participantName: "AGL Energy", fuelTech: "gas_ccgt", fuelGroup: "gas", regionId: "SA1", state: "SA", latitude: -34.7790, longitude: 138.5240, maxCapacityMW: 800, registeredCapacityMW: 800, currentOutputMW: 300, dispatchType: "scheduled", status: "operating", commissionedYear: 1976 },
  { duid: "MORTLK11", stationName: "Mortlake", participantName: "Origin Energy", fuelTech: "gas_ocgt", fuelGroup: "gas", regionId: "VIC1", state: "VIC", latitude: -38.2000, longitude: 142.8330, maxCapacityMW: 566, registeredCapacityMW: 566, currentOutputMW: 0, dispatchType: "scheduled", status: "operating", commissionedYear: 2012 },
  { duid: "JBUTTERS", stationName: "Jeeralang", participantName: "EnergyAustralia", fuelTech: "gas_ocgt", fuelGroup: "gas", regionId: "VIC1", state: "VIC", latitude: -38.3180, longitude: 146.4890, maxCapacityMW: 449, registeredCapacityMW: 449, currentOutputMW: 0, dispatchType: "scheduled", status: "operating", commissionedYear: 1979 },
  { duid: "BDL01", stationName: "Braemar", participantName: "Arrow Energy", fuelTech: "gas_ocgt", fuelGroup: "gas", regionId: "QLD1", state: "QLD", latitude: -27.1260, longitude: 150.8210, maxCapacityMW: 504, registeredCapacityMW: 504, currentOutputMW: 100, dispatchType: "scheduled", status: "operating", commissionedYear: 2006 },
  { duid: "OSBAG", stationName: "Osborne", participantName: "Origin Energy", fuelTech: "gas_ccgt", fuelGroup: "gas", regionId: "SA1", state: "SA", latitude: -34.8160, longitude: 138.5180, maxCapacityMW: 180, registeredCapacityMW: 180, currentOutputMW: 120, dispatchType: "scheduled", status: "operating", commissionedYear: 1998 },
  { duid: "SNOWY_G1", stationName: "Colongra Gas", participantName: "Snowy Hydro", fuelTech: "gas_ocgt", fuelGroup: "gas", regionId: "NSW1", state: "NSW", latitude: -33.2400, longitude: 151.5100, maxCapacityMW: 667, registeredCapacityMW: 667, currentOutputMW: 0, dispatchType: "scheduled", status: "operating", commissionedYear: 2009 },

  // ─── Wind ───
  { duid: "MACARTH1", stationName: "Macarthur Wind Farm", participantName: "AGL Energy", fuelTech: "wind", fuelGroup: "wind", regionId: "VIC1", state: "VIC", latitude: -38.0700, longitude: 142.1680, maxCapacityMW: 420, registeredCapacityMW: 420, currentOutputMW: 180, dispatchType: "semi-scheduled", status: "operating", commissionedYear: 2013 },
  { duid: "COPRWF1", stationName: "Coopers Gap Wind Farm", participantName: "AGL Energy", fuelTech: "wind", fuelGroup: "wind", regionId: "QLD1", state: "QLD", latitude: -26.7490, longitude: 151.5300, maxCapacityMW: 453, registeredCapacityMW: 453, currentOutputMW: 210, dispatchType: "semi-scheduled", status: "operating", commissionedYear: 2021 },
  { duid: "SNWF1", stationName: "Snowtown Wind Farm", participantName: "Tilt Renewables", fuelTech: "wind", fuelGroup: "wind", regionId: "SA1", state: "SA", latitude: -33.7760, longitude: 138.5150, maxCapacityMW: 369, registeredCapacityMW: 369, currentOutputMW: 150, dispatchType: "semi-scheduled", status: "operating", commissionedYear: 2014 },
  { duid: "HDWF1", stationName: "Hallett Wind Farm", participantName: "AGL Energy", fuelTech: "wind", fuelGroup: "wind", regionId: "SA1", state: "SA", latitude: -33.3620, longitude: 138.7700, maxCapacityMW: 351, registeredCapacityMW: 351, currentOutputMW: 120, dispatchType: "semi-scheduled", status: "operating", commissionedYear: 2010 },
  { duid: "WGWF1", stationName: "Wattle Range Wind Farm", participantName: "Engie", fuelTech: "wind", fuelGroup: "wind", regionId: "SA1", state: "SA", latitude: -37.4500, longitude: 140.7600, maxCapacityMW: 91, registeredCapacityMW: 91, currentOutputMW: 42, dispatchType: "semi-scheduled", status: "operating", commissionedYear: 2011 },
  { duid: "MUSSELR1", stationName: "Musselroe Wind Farm", participantName: "Woolnorth Renewables", fuelTech: "wind", fuelGroup: "wind", regionId: "TAS1", state: "TAS", latitude: -40.7930, longitude: 148.0720, maxCapacityMW: 168, registeredCapacityMW: 168, currentOutputMW: 80, dispatchType: "semi-scheduled", status: "operating", commissionedYear: 2013 },
  { duid: "CAPTL_WF", stationName: "Capital Wind Farm", participantName: "Infigen Energy", fuelTech: "wind", fuelGroup: "wind", regionId: "NSW1", state: "NSW", latitude: -34.9670, longitude: 149.5300, maxCapacityMW: 141, registeredCapacityMW: 141, currentOutputMW: 60, dispatchType: "semi-scheduled", status: "operating", commissionedYear: 2009 },
  { duid: "BANGO1", stationName: "Bango Wind Farm", participantName: "CWP Renewables", fuelTech: "wind", fuelGroup: "wind", regionId: "NSW1", state: "NSW", latitude: -34.5980, longitude: 148.8390, maxCapacityMW: 244, registeredCapacityMW: 244, currentOutputMW: 100, dispatchType: "semi-scheduled", status: "operating", commissionedYear: 2022 },
  { duid: "STWF1", stationName: "Stockyard Hill Wind Farm", participantName: "Goldwind", fuelTech: "wind", fuelGroup: "wind", regionId: "VIC1", state: "VIC", latitude: -37.6700, longitude: 143.3500, maxCapacityMW: 530, registeredCapacityMW: 530, currentOutputMW: 250, dispatchType: "semi-scheduled", status: "operating", commissionedYear: 2021 },
  { duid: "DUNDOWF", stationName: "Dundonnell Wind Farm", participantName: "Tilt Renewables", fuelTech: "wind", fuelGroup: "wind", regionId: "VIC1", state: "VIC", latitude: -37.8100, longitude: 142.6900, maxCapacityMW: 336, registeredCapacityMW: 336, currentOutputMW: 140, dispatchType: "semi-scheduled", status: "operating", commissionedYear: 2020 },
  { duid: "MOORWF", stationName: "Moorabool Wind Farm", participantName: "Goldwind", fuelTech: "wind", fuelGroup: "wind", regionId: "VIC1", state: "VIC", latitude: -37.6600, longitude: 144.0900, maxCapacityMW: 312, registeredCapacityMW: 312, currentOutputMW: 130, dispatchType: "semi-scheduled", status: "operating", commissionedYear: 2019 },

  // ─── Solar ───
  { duid: "LKBWN1", stationName: "Limondale Sun Farm", participantName: "Canadian Solar", fuelTech: "solar_utility", fuelGroup: "solar", regionId: "NSW1", state: "NSW", latitude: -33.5860, longitude: 145.3220, maxCapacityMW: 313, registeredCapacityMW: 313, currentOutputMW: 200, dispatchType: "semi-scheduled", status: "operating", commissionedYear: 2020 },
  { duid: "DAYDWN1", stationName: "Daydream Solar Farm", participantName: "Edify Energy", fuelTech: "solar_utility", fuelGroup: "solar", regionId: "QLD1", state: "QLD", latitude: -19.8770, longitude: 147.0500, maxCapacityMW: 180, registeredCapacityMW: 180, currentOutputMW: 120, dispatchType: "semi-scheduled", status: "operating", commissionedYear: 2018 },
  { duid: "CLERMS1", stationName: "Clermont Solar Farm", participantName: "Wirsol", fuelTech: "solar_utility", fuelGroup: "solar", regionId: "QLD1", state: "QLD", latitude: -22.8200, longitude: 147.6100, maxCapacityMW: 75, registeredCapacityMW: 75, currentOutputMW: 50, dispatchType: "semi-scheduled", status: "operating", commissionedYear: 2019 },
  { duid: "BNGSF1", stationName: "Bungala Solar Farm", participantName: "Enel Green Power", fuelTech: "solar_utility", fuelGroup: "solar", regionId: "SA1", state: "SA", latitude: -31.2770, longitude: 137.0010, maxCapacityMW: 275, registeredCapacityMW: 275, currentOutputMW: 180, dispatchType: "semi-scheduled", status: "operating", commissionedYear: 2018 },
  { duid: "SUNRSF1", stationName: "Sunraysia Solar Farm", participantName: "Maoneng", fuelTech: "solar_utility", fuelGroup: "solar", regionId: "NSW1", state: "NSW", latitude: -34.0900, longitude: 142.1700, maxCapacityMW: 255, registeredCapacityMW: 255, currentOutputMW: 160, dispatchType: "semi-scheduled", status: "operating", commissionedYear: 2022 },
  { duid: "WEMENSF", stationName: "Western Melbourne Solar Farm", participantName: "ACCIONA", fuelTech: "solar_utility", fuelGroup: "solar", regionId: "VIC1", state: "VIC", latitude: -37.7200, longitude: 144.4500, maxCapacityMW: 85, registeredCapacityMW: 85, currentOutputMW: 55, dispatchType: "semi-scheduled", status: "operating", commissionedYear: 2021 },
  { duid: "MRSF1", stationName: "Moree Solar Farm", participantName: "Fotowatio", fuelTech: "solar_utility", fuelGroup: "solar", regionId: "NSW1", state: "NSW", latitude: -29.4490, longitude: 149.8010, maxCapacityMW: 56, registeredCapacityMW: 56, currentOutputMW: 35, dispatchType: "semi-scheduled", status: "operating", commissionedYear: 2016 },
  { duid: "COLGNSF", stationName: "Columboola Solar Farm", participantName: "Neoen", fuelTech: "solar_utility", fuelGroup: "solar", regionId: "QLD1", state: "QLD", latitude: -26.5100, longitude: 150.2400, maxCapacityMW: 151, registeredCapacityMW: 151, currentOutputMW: 95, dispatchType: "semi-scheduled", status: "operating", commissionedYear: 2022 },
  { duid: "WRSF1", stationName: "Western Downs Solar Farm", participantName: "Neoen", fuelTech: "solar_utility", fuelGroup: "solar", regionId: "QLD1", state: "QLD", latitude: -26.7900, longitude: 151.0200, maxCapacityMW: 400, registeredCapacityMW: 400, currentOutputMW: 280, dispatchType: "semi-scheduled", status: "operating", commissionedYear: 2022 },

  // ─── Hydro ───
  { duid: "TUMUT3", stationName: "Tumut 3", participantName: "Snowy Hydro", fuelTech: "hydro", fuelGroup: "hydro", regionId: "NSW1", state: "NSW", latitude: -35.7690, longitude: 148.4030, maxCapacityMW: 1500, registeredCapacityMW: 1500, currentOutputMW: 400, dispatchType: "scheduled", status: "operating", commissionedYear: 1973 },
  { duid: "MURRAY1", stationName: "Murray 1", participantName: "Snowy Hydro", fuelTech: "hydro", fuelGroup: "hydro", regionId: "NSW1", state: "NSW", latitude: -36.2910, longitude: 148.1170, maxCapacityMW: 950, registeredCapacityMW: 950, currentOutputMW: 300, dispatchType: "scheduled", status: "operating", commissionedYear: 1966 },
  { duid: "GORDON", stationName: "Gordon Power Station", participantName: "Hydro Tasmania", fuelTech: "hydro", fuelGroup: "hydro", regionId: "TAS1", state: "TAS", latitude: -42.7450, longitude: 145.9720, maxCapacityMW: 432, registeredCapacityMW: 432, currentOutputMW: 200, dispatchType: "scheduled", status: "operating", commissionedYear: 1978 },
  { duid: "REECE1", stationName: "Reece Power Station", participantName: "Hydro Tasmania", fuelTech: "hydro", fuelGroup: "hydro", regionId: "TAS1", state: "TAS", latitude: -41.7870, longitude: 145.5500, maxCapacityMW: 231, registeredCapacityMW: 231, currentOutputMW: 100, dispatchType: "scheduled", status: "operating", commissionedYear: 1986 },
  { duid: "JBTOWER", stationName: "John Butters", participantName: "Hydro Tasmania", fuelTech: "hydro", fuelGroup: "hydro", regionId: "TAS1", state: "TAS", latitude: -41.8740, longitude: 146.0560, maxCapacityMW: 144, registeredCapacityMW: 144, currentOutputMW: 70, dispatchType: "scheduled", status: "operating", commissionedYear: 1940 },
  { duid: "DARTM1", stationName: "Dartmouth", participantName: "AGL Energy", fuelTech: "hydro", fuelGroup: "hydro", regionId: "VIC1", state: "VIC", latitude: -36.5440, longitude: 147.4950, maxCapacityMW: 180, registeredCapacityMW: 180, currentOutputMW: 50, dispatchType: "scheduled", status: "operating", commissionedYear: 1977 },

  // ─── Battery ───
  { duid: "HPRG1", stationName: "Hornsdale Power Reserve", participantName: "Neoen", fuelTech: "battery_discharging", fuelGroup: "battery", regionId: "SA1", state: "SA", latitude: -33.0700, longitude: 138.5200, maxCapacityMW: 150, registeredCapacityMW: 150, currentOutputMW: 50, dispatchType: "scheduled", status: "operating", commissionedYear: 2017 },
  { duid: "VBBG1", stationName: "Victorian Big Battery", participantName: "Neoen", fuelTech: "battery_discharging", fuelGroup: "battery", regionId: "VIC1", state: "VIC", latitude: -38.2100, longitude: 144.3300, maxCapacityMW: 300, registeredCapacityMW: 300, currentOutputMW: 0, dispatchType: "scheduled", status: "operating", commissionedYear: 2021 },
  { duid: "BESS1", stationName: "Wallgrove Battery", participantName: "Transgrid", fuelTech: "battery_discharging", fuelGroup: "battery", regionId: "NSW1", state: "NSW", latitude: -33.8600, longitude: 150.8600, maxCapacityMW: 50, registeredCapacityMW: 50, currentOutputMW: 0, dispatchType: "scheduled", status: "operating", commissionedYear: 2022 },
  { duid: "WBESS", stationName: "Waratah Super Battery", participantName: "Akaysha Energy", fuelTech: "battery_discharging", fuelGroup: "battery", regionId: "NSW1", state: "NSW", latitude: -32.7800, longitude: 151.4600, maxCapacityMW: 850, registeredCapacityMW: 850, currentOutputMW: 0, dispatchType: "scheduled", status: "operating", commissionedYear: 2024 },
  { duid: "DALRYMPLE", stationName: "Dalrymple North BESS", participantName: "ElectraNet", fuelTech: "battery_discharging", fuelGroup: "battery", regionId: "SA1", state: "SA", latitude: -33.1700, longitude: 138.7800, maxCapacityMW: 30, registeredCapacityMW: 30, currentOutputMW: 0, dispatchType: "scheduled", status: "operating", commissionedYear: 2018 },
  { duid: "BWBESS", stationName: "Bouldercombe Battery", participantName: "CS Energy", fuelTech: "battery_discharging", fuelGroup: "battery", regionId: "QLD1", state: "QLD", latitude: -23.5600, longitude: 150.4800, maxCapacityMW: 200, registeredCapacityMW: 200, currentOutputMW: 0, dispatchType: "scheduled", status: "commissioning", commissionedYear: 2025 },

  // ─── Biomass / Other ───
  { duid: "INVICTA1", stationName: "Invicta Sugar Mill", participantName: "Wilmar", fuelTech: "biomass", fuelGroup: "biomass", regionId: "QLD1", state: "QLD", latitude: -19.5800, longitude: 147.4100, maxCapacityMW: 32, registeredCapacityMW: 32, currentOutputMW: 15, dispatchType: "non-scheduled", status: "operating", commissionedYear: 2000 },
  { duid: "CONDONG1", stationName: "Condong Sugar Mill", participantName: "Sunshine Sugar", fuelTech: "biomass", fuelGroup: "biomass", regionId: "NSW1", state: "NSW", latitude: -28.3200, longitude: 153.4300, maxCapacityMW: 30, registeredCapacityMW: 30, currentOutputMW: 12, dispatchType: "non-scheduled", status: "operating", commissionedYear: 2005 },
];
